#!/usr/bin/env python3
"""Generate bolt-public-pages' src/styles/templates-page.css — the /resources/templates
catalog on the reviewed staging design (marketing/templates/index.html).
Hand-mapped (production keeps the catalog-* names and renames the hero to
.tpl-hero); the footer / prompt box rules are reused from use-case-route.css.

    python3 tools/port-templates-css.py ~/Projects/bolt-public-pages
"""
import re, sys, pathlib
repo = pathlib.Path(sys.argv[1]).expanduser()
P = '.use-case-page[data-page="resources-templates"]'
NOISE = """url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 256 256'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='256' height='256' filter='url(%23n)'/%3E%3C/svg%3E")"""
shared = (pathlib.Path(__file__).resolve().parent / 'port-use-cases-css.py').read_text()
NAV = shared[shared.index("NAV = '''")+9:shared.index("'''\nBODY")]
CSS = '''HEAD
/* ── /resources/templates (the catalog) — the reviewed staging design
   (garyliusf/Enterprise marketing/templates/index.html), ported 2026-10-05.
   GENERATED by tools/port-templates-css.py in the sandbox repo. Loaded by the
   templates-marketplace section, which only this page uses; EVERY rule is
   scoped under the page wrapper's data-page. Colours come from the --sc-*
   tokens (no data-theme = the dark literals the sections ship;
   html[data-theme="light"] flips them). ──────────────────────────────── */

P {
  --sc-nav-overlap: 69px;
  --sub-to-cta: 32px;
  --cta-min-w: 180px;
  background: var(--sc-ground, #000);
  color: var(--sc-ink, #fff);
  font-family: var(--sc-font-sans, 'Schibsted Grotesk', sans-serif);
  line-height: normal;
}
@media (max-width: 768px) { P { --sub-to-cta: 24px; --cta-min-w: 220px; } }
P main button,
P main input,
P .re-prompt-submit,
P .catalog-card-cta,
P .catalog-card-demo { font-family: var(--sc-font-sans, 'Schibsted Grotesk', sans-serif); }
NAV
/* ── Labels on the sans label face ── */
P .section-eyebrow,
P .footer-eyebrow { font-family: var(--sc-font-label, 'Schibsted Grotesk', sans-serif); font-weight: var(--sc-label-weight, 700); font-size: var(--sc-eyebrow-size, 13px); }
P .catalog-card-tag,
P .catalog-empty { font-family: var(--sc-font-label, 'Schibsted Grotesk', sans-serif); font-weight: var(--sc-label-weight, 700); }
P .catalog-filter-btn { font-family: var(--sc-font-label, 'Schibsted Grotesk', sans-serif); font-weight: 600; }   /* pinned: 700 too bold, 500 too thin on the category row (Gary) */
P .catalog-search,
P .catalog-search::placeholder,
P .catalog-card-overlay span { font-family: var(--sc-font-label, 'Schibsted Grotesk', sans-serif); font-weight: 500; }

/* ── Section units ── */
@media (max-width: 1024px) { P .section { padding: 64px 0; } }
@media (max-width: 768px) { P .section { padding: 48px 0; } }

/* ── Hero (templates-hero): the compact catalog hero — PAGE EXCEPTION (Gary):
   42vh / 430px, copy riding high in the gradient's navy crown ── */
P .tpl-hero {
  min-height: calc(min(42vh, 430px) + var(--sc-nav-overlap, 0px));
  min-height: calc(min(42dvh, 430px) + var(--sc-nav-overlap, 0px));
  justify-content: flex-start;
  padding: calc(clamp(90px, calc(24px + 8.5vh), 148px) + var(--sc-nav-overlap, 0px)) 0 clamp(8px, 1.1vh, 26px);
  background:
    radial-gradient(ellipse 105% 62% at 50% -18%, rgba(20,136,252,0.22) 0%, rgba(20,136,252,0.05) 55%, transparent 78%),
    #050507;
}
P .tpl-hero::before {
  content: ""; position: absolute; inset: 0; z-index: 0; pointer-events: none;
  background-image: NOISE;
  background-size: 256px 256px; opacity: 0.05;
  -webkit-mask-image: linear-gradient(180deg, #000 65%, rgba(0,0,0,0) 95%);
          mask-image: linear-gradient(180deg, #000 65%, rgba(0,0,0,0) 95%);
}
P .tpl-hero-grid { display: none !important; }   /* the wallpaper is retired at every width (Gary, 2026-09-29) */
P .tpl-hero .hero-dither {
  position: absolute; inset: 0; width: 100%; height: 100%; z-index: 1; pointer-events: none;
  -webkit-mask-image: linear-gradient(180deg, #000 55%, rgba(0,0,0,0) 92%);
          mask-image: linear-gradient(180deg, #000 55%, rgba(0,0,0,0) 92%);
}
P .tpl-hero-inner { margin-top: 20px; gap: 24px; }   /* eases the copy 20px off the hero's top padding (page exception) */
P .tpl-hero .hero-h1 { font-size: 66px; font-weight: 500; line-height: 1.1; letter-spacing: -0.5px; color: #fff; }
P .tpl-hero .hero-subtitle { font-size: clamp(16px, 1.4vw, 20px); line-height: 1.4; color: #ABABAB; max-width: 640px; }
P .tpl-hero-inner > .hero-subtitle { margin-top: -4px; }   /* H1→subtitle 20 (12 on phones) */
@media (max-width: 1024px) {
  P .tpl-hero .hero-h1 { font-size: 51px; }
  P .tpl-hero .hero-subtitle { font-size: 18px; }
}
@media (max-width: 768px) {
  P .tpl-hero { min-height: 0; padding: calc(52px + var(--sc-nav-overlap, 0px)) 0 96px; }   /* family proportion: headline up, dome room below the copy so the subtitle ends at ~73% of the box, on blue (was 80/20: white on the white rim) */
  P .tpl-hero-inner { gap: 16px; }
  P .tpl-hero .hero-h1 { font-size: clamp(37px, 10.45vw, 51px); }
  P .tpl-hero .hero-subtitle { font-size: 16px; }
}

/* ── Catalog ── */
P .catalog-section { background: var(--sc-band, #050508); padding-top: clamp(8px, calc(6vh - 40px), 32px); padding-bottom: clamp(24px, 4vh, 48px); }
P .catalog-filters-wrap::after { display: none; }   /* the overflow cue is the mask below, not an overlay */
P .catalog-filters {
  border-bottom-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.08);
  -webkit-mask-image: linear-gradient(to right, #000 0%, #000 calc(100% - 176px), rgba(0,0,0,0.5) calc(100% - 104px), rgba(0,0,0,0.14) calc(100% - 52px), rgba(0,0,0,0) calc(100% - 10px));
          mask-image: linear-gradient(to right, #000 0%, #000 calc(100% - 176px), rgba(0,0,0,0.5) calc(100% - 104px), rgba(0,0,0,0.14) calc(100% - 52px), rgba(0,0,0,0) calc(100% - 10px));
}
P .catalog-filters-wrap.at-end .catalog-filters { -webkit-mask-image: none; mask-image: none; }
P .catalog-filter-btn { color: var(--sc-text-desc, rgba(255,255,255,0.55)); }
P .catalog-filter-btn:hover { color: var(--sc-ink, #fff); }
P .catalog-filter-btn.is-active { color: #1488FC; font-weight: 700; }   /* brand blue a step bolder than the row, both themes (Gary): the mint barely registered on white, the AA navy read dull */
html[data-theme="light"] P .catalog-filter-btn.is-active { color: #0f6fd0; }   /* the hover blue: brand #1488FC is 3.5:1 on white, an 11px label needs 4.5:1 (AA); #0f6fd0 is 4.99:1 and reads the same. Dark keeps brand (5.8:1). */
P .catalog-search-wrap { background: transparent; border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.06); }
P .catalog-search-wrap:hover { border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.18); }
P .catalog-search-wrap:focus-within { border-color: rgba(20,136,252,0.55); background: transparent; }
P .catalog-search-wrap svg { color: var(--sc-text-desc, rgba(255,255,255,0.55)); }
P .catalog-search { color: var(--sc-ink, #fff); letter-spacing: 0.8px; }
P .catalog-search::placeholder { color: var(--sc-text-desc, rgba(255,255,255,0.55)); text-transform: none; letter-spacing: 0.3px; }   /* sentence case, not all-caps (Gary) */
@media (max-width: 1024px) { P .catalog-search { font-size: 14px; } }
@media (max-width: 768px) { P .catalog-search { font-size: 13px; letter-spacing: 0.3px; } }
P .catalog-card-preview { border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.08); }
P :where(a.catalog-card, .catalog-card-link):hover .catalog-card-preview { border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.2); }
P .catalog-card-overlay span { color: var(--sc-ink, #fff); }
P .catalog-card-name { font-family: var(--sc-font-sans, 'Inter', sans-serif); color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.92); }   /* the variants sheet pins Inter */
P .catalog-card-tag { color: var(--sc-text-muted, rgba(255,255,255,0.5)); }
P .catalog-empty { color: var(--sc-text-faint, rgba(255,255,255,0.4)); border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.10); }
/* the action row is production-only (the staging card has no buttons): the ghost on the tokens */
P .catalog-card-demo { border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.22); color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.8); }
P .catalog-card-demo:hover { border-color: rgba(var(--sc-ink-rgb, 255, 255, 255), 0.4); color: var(--sc-ink, #fff); }
@media (max-width: 768px) {
  P .catalog-section { padding-top: 24px; padding-bottom: 48px; }   /* seam trim under the hero + the phone section unit (restated: the section's own clamp wins over the .section rule above) */
  P .catalog-filters { gap: 6px; }
  P .catalog-search-wrap { margin-left: 0; width: 100%; padding: 12px 14px; }
}

/* ═══ LIGHT — the staging page's own theme-keyed rules ═══ */
html[data-theme="light"] P .tpl-hero {
  background:
    radial-gradient(140% 150% at 50% -32%,
      #04091a 0%, #061129 26%, #081b3f 38%, #0b2a58 48%, #0f3c78 56%,
      #155a9e 62%, #1f74bd 67%, rgba(58,142,205,0.8) 72%,
      rgba(108,178,224,0.45) 78%, rgba(150,205,238,0.15) 82.5%,
      rgba(175,220,243,0) 86%),
    linear-gradient(180deg,
      #2f80c4 45%, #5da5d8 58%, #8ec6e8 68%, #bcdcf1 76%,
      #d6e9f7 81.5%, #e6f1fa 85.5%, #f0f7fc 88.5%, #f7fbfe 91%,
      #fbfdfe 93%, #fdfeff 94.5%, #fff 96%), #fff;
}
html[data-theme="light"] P .tpl-hero .hero-subtitle { color: rgba(255,255,255,0.94); }
html[data-theme="light"] P .catalog-card-preview { background: var(--sc-surface); }   /* the near-black bg peeked around the thumb's rounded edges as a dark frame on light */
/* the dark bottom scrim + bare ink label read muddy over the mostly-light shots: a white wash and a pill chip */
html[data-theme="light"] P .catalog-card-overlay { background: linear-gradient(180deg, rgba(255,255,255,0) 60%, rgba(255,255,255,0.72) 88%, rgba(255,255,255,0.92) 100%); }   /* the wash starts at 60% (was 40%: it covered most of the shot — Gary) */
html[data-theme="light"] P .catalog-card-overlay span { background: #fff; padding: 9px 16px; border-radius: 999px; border: 1px solid rgba(var(--sc-ink-rgb), 0.08); box-shadow: 0 4px 14px rgba(15,26,42,0.12); }
'''
css = CSS.replace('NAV', NAV).replace('HEAD', '').replace('NOISE', NOISE)
css = re.sub(r'(?m)^P ', P + ' ', css).replace(' P ', ' ' + P + ' ').replace('{ P {', '{ ' + P + ' {')
# footer + prompt box + pills from the use-case route (same footer-cta variant)
route = (repo / 'src/styles/use-case-route.css').read_text()
RP = '.use-case-page.use-case-page[data-page="use-case"]'
def blocks(src):
    i, n, out = 0, len(src), []
    while i < n:
        j = src.find('{', i)
        if j < 0: break
        head = src[i:j]; depth, k = 1, j + 1
        while k < n and depth:
            if src[k] == '{': depth += 1
            elif src[k] == '}': depth -= 1
            k += 1
        out.append((head.strip(), src[j + 1:k - 1])); i = k
    return out
FOOT = re.compile(r'\.(footer-section|footer-eyebrow|footer-headline|footer-subtitle|footer-cta-wrap|footer-prompt-stack|footer-cta-pills|footer-spacer|re-prompt-shell|re-prompt-input|re-prompt-actions|re-prompt-submit|hero-pills)')
def pick(head, body):
    head = re.sub(r'/\*.*?\*/', '', head, flags=re.S).strip()
    if head.startswith('@media'):
        inner = '\n'.join(x for h, b in blocks(body) for x in pick(h, b))
        return [f'{head} {{\n{inner}\n}}'] if inner.strip() else []
    if head.startswith('@') or not head: return []
    sels = [s.strip() for s in head.split(',') if FOOT.search(s)]
    return [', '.join(s.replace(RP, P) for s in sels) + ' {' + body + '}'] if sels else []
foot = [x for h, b in blocks(route) for x in pick(h, b)]
css += '\n/* ═══ Footer CTA + prompt box — the use-case route\'s rules (the same footer-cta "use-case" variant), re-scoped ═══ */\n' + '\n'.join(foot) + '\n'
css += ('''
/* this page's footer: no hairline, the staging measure */
P .footer-section { border-top: 0; }
P .footer-section .footer-subtitle { max-width: 640px !important; white-space: normal; }
@media (max-width: 768px) {
  P .footer-section { padding-top: 48px; padding-left: 0; padding-right: 0; }
  P .footer-section > *:not(canvas):not(.footer-cta-wrap):not(.hero-pills) { padding-left: 12px; padding-right: 12px; box-sizing: border-box; width: 100%; }
  P .footer-cta-wrap { padding-left: 16px; padding-right: 16px; box-sizing: border-box; }
  P .footer-section .footer-subtitle { max-width: 380px !important; }
}
''').replace('P ', P + ' ')
assert RP not in css   # every reused rule re-scoped
(repo / 'src/styles/templates-page.css').write_text(css)
print(f'wrote templates-page.css: {len(css.splitlines())} lines ({len(foot)} footer rules reused)')
