#!/usr/bin/env python3
"""Generate bolt-public-pages' src/styles/builder-light-kit.css — the reviewed
light/dark design for pages composed in the CMS page builder from the shared
sections (first page: /platform/features/slides).

Nothing here is new design. It re-scopes, per component, rules that already
shipped: the use-case route's generated rules (card grid, how-it-works, FAQ,
footer CTA, section scaffolding, over-hero nav — use-case-route.css) and the
/use-cases directory's hero-short treatment (port-use-cases-css.py). Only the
video showcase block is written here.

Add a page id to PAGES and re-run to bring another builder page onto it:

    python3 tools/port-builder-light-css.py ~/Projects/bolt-public-pages
"""
import re, sys, pathlib
repo = pathlib.Path(sys.argv[1]).expanduser()
PAGES = ['platform-features-slides']
# doubled class = (0,3,0), the use-case route's own weight, so the re-scoped rules keep their order against the base
P = '.use-case-page.use-case-page:is(' + ', '.join(f'[data-page="{p}"]' for p in PAGES) + ')'
RP = '.use-case-page.use-case-page[data-page="use-case"]'
route = (repo / 'src/styles/use-case-route.css').read_text()
ucgen = (pathlib.Path(__file__).parent / 'port-use-cases-css.py').read_text()
NOISE = re.search(r'^NOISE = """(.*?)"""', ucgen, re.S | re.M).group(1)

def blocks(src):
    i, n, out = 0, len(src), []
    while i < n:
        j = src.find('{', i)
        if j < 0: break
        head = src[i:j]; depth, k = 1, j + 1
        while k < n and depth:
            if src[k] == '{': depth += 1
            elif src[k] == '}': depth -= 1
            k += 1
        out.append((head.strip(), src[j + 1:k - 1])); i = k
    return out

# components the builder sections share with the use-case route …
KEEP = re.compile(r'\.(unlock|unlocks-|card-grid-3|connect-pixels|has-connect-pixels|how-|ms-faq|footer-|re-prompt|hero-pills|section|dsa-reveal|hero-btn-|btn-pixel-canvas|mkt-nav)')
# … minus the ones only that route renders
DROP = re.compile(r'\.(hero-section|hero-prompt|hero-inner|hero-content|hero-text|hero-h1|hero-subtitle|hero-eyebrow|hero-overlay|hero-pixel|hero-dither|included|testi|prompt-card|template|feat-|success|quote|why-|stats|stat-cell|deploy|card-form-strip|footer-email|footer-form-row|footer-links|footer-link|footer-copyright|footer-cta-btn-top|split)')
def split_top(head):
    """split a selector list on its top-level commas only (not the ones inside :is() / :not())"""
    out, depth, cur = [], 0, ''
    for ch in head:
        if ch == '(': depth += 1
        elif ch == ')': depth -= 1
        if ch == ',' and depth == 0: out.append(cur.strip()); cur = ''
        else: cur += ch
    if cur.strip(): out.append(cur.strip())
    return out
used_kf = set()
def pick(head, body):
    head = re.sub(r'/\*.*?\*/', '', head, flags=re.S).strip()
    if head.startswith('@media'):
        inner = '\n'.join(x for h, b in blocks(body) for x in pick(h, b))
        return [f'{head} {{\n{inner}\n}}'] if inner.strip() else []
    if head.startswith('@') or not head: return []
    sels = []
    for s in split_top(head):
        if RP not in s: continue
        rest = s.replace(RP, '')
        # a selector LIST inside :is() mixes kept and dropped components — keep it whole, the extra alternatives match nothing here
        ok = KEEP.search(rest) and (':is(' in rest or not DROP.search(rest))
        if rest.strip() == '' or ok: sels.append(s.replace(RP, P))
    if not sels: return []
    used_kf.update(re.findall(r'\buc-[\w-]+', body))
    return [', '.join(sels) + ' {' + body + '}']
picked = [x for h, b in blocks(route) for x in pick(h, b)]
keyframes = [f'{h} {{{b}}}' for h, b in blocks(route) if h.startswith('@keyframes') and h.split()[1] in used_kf]

HEAD = '''/* ── Builder light kit — the reviewed light/dark design for pages built in the
   CMS page builder from the shared sections. GENERATED by
   tools/port-builder-light-css.py in the sandbox repo (garyliusf/Enterprise):
   do not hand-edit, change the generator and re-run. Imported by BuiltPage;
   EVERY rule is scoped to the listed page ids, so it is inert on every other
   page. Component rules are the use-case route's (use-case-route.css) and the
   /use-cases hero-short treatment, re-scoped; only the video showcase block is
   written in the generator. Dark is the base (no data-theme = the dark token
   literals), html[data-theme="light"] flips. Pages: PAGELIST ─────────────── */

P {
  --sc-nav-overlap: 69px;   /* the bar's BOX: 68px + its 1px hairline */
  line-height: normal;      /* the site's Tailwind base sets 1.5; the staging pages are browser-normal */
}
'''
HERO = '''
/* ═══ Hero (hero-short) — the /use-cases directory treatment: the family box + the nav overlap, copy centred ═══ */
P .uc-hero {
  min-height: calc(min(65vh, 684px) + var(--sc-nav-overlap, 0px));
  min-height: calc(min(65dvh, 684px) + var(--sc-nav-overlap, 0px));
  padding: calc(clamp(90px, calc(24px + 8.5vh), 148px) + var(--sc-nav-overlap, 0px)) 0 clamp(72px, 8vh, 112px);
  background: var(--sc-ground, #050507) radial-gradient(ellipse 70% 50% at 50% 30%, rgba(20,136,252,0.18) 0%, transparent 70%);
}
P .uc-hero::before {
  content: ""; position: absolute; inset: 0; z-index: 0; pointer-events: none;
  background-image: NOISE;
  background-size: 256px 256px; opacity: 0.05;
  -webkit-mask-image: linear-gradient(180deg, #000 65%, rgba(0,0,0,0) 95%);
          mask-image: linear-gradient(180deg, #000 65%, rgba(0,0,0,0) 95%);
}
html:not([data-theme="light"]) P .uc-hero::after {
  content: ""; position: absolute; left: 0; right: 0; bottom: 0; height: 120px; z-index: 2; pointer-events: none;
  background: linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.5) 55%, #000 100%);
}
P .uc-hero-dots { display: none; }   /* the dither is the hero's pixel layer */
P .uc-hero .hero-dither {
  position: absolute; inset: 0; width: 100%; height: 100%; z-index: 1; pointer-events: none;
  -webkit-mask-image: linear-gradient(180deg, #000 55%, rgba(0,0,0,0) 90%);
          mask-image: linear-gradient(180deg, #000 55%, rgba(0,0,0,0) 90%);
}
P .uc-hero-h1 { font-size: 66px; line-height: 1.1; letter-spacing: -0.5px; color: #fff; }
P .uc-hero-subtitle { font-size: clamp(16px, 1.4vw, 20px); line-height: 1.5; color: #ABABAB; max-width: 640px; }
/* hero stack standard: H1→subtitle 20 / 20 / 12, subtitle→CTA 32 / 32 / 24 — net of the 24px stack gap */
P .uc-hero-inner > .uc-hero-subtitle { margin-top: -4px; }
P .uc-hero .hero-btn-group { margin-top: 8px; }
P .uc-hero .hero-btn-group .hero-btn-primary { min-width: var(--cta-min-w, 180px); }
@media (max-width: 1024px) {
  P .uc-hero-h1 { font-size: 51px; }
  P .uc-hero-subtitle { font-size: 18px; }
}
@media (max-width: 768px) {
  P .uc-hero { min-height: 0; padding: calc(80px + var(--sc-nav-overlap, 0px)) 0 68px; }
  P .uc-hero-h1 { font-size: clamp(37px, 10.45vw, 51px); }
  P .uc-hero-subtitle { font-size: 16px; }
  P .uc-hero-inner > .uc-hero-subtitle { margin-top: -12px; }
  P .uc-hero .hero-btn-group { margin-top: 0; }
}
/* light: the approved deep hero (the bowl) — a wide radial dome over a smooth light ramp, white in the last fifth */
html[data-theme="light"] P .uc-hero {
  background:
    radial-gradient(140% 150% at 50% -32%,
      #04091a 0%, #061129 26%, #081b3f 38%, #0b2a58 48%, #0f3c78 56%,
      #155a9e 62%, #1f74bd 67%, rgba(58,142,205,0.8) 72%,
      rgba(108,178,224,0.45) 78%, rgba(150,205,238,0.15) 82.5%,
      rgba(175,220,243,0) 86%),
    linear-gradient(180deg,
      #2f80c4 45%, #5da5d8 58%, #8ec6e8 68%, #bcdcf1 76%,
      #d6e9f7 81.5%, #e6f1fa 85.5%, #f0f7fc 88.5%, #f7fbfe 91%,
      #fbfdfe 93%, #fdfeff 94.5%, #fff 96%), #fff;
}
html[data-theme="light"] P .uc-hero-subtitle { color: rgba(255,255,255,0.94); }
'''
VIDEO = '''
/* ═══ Video showcase (hero-video) — written here; the card is dark product art in both themes ═══ */
/* the section sits directly under the hero on the same ground: one unit at the seam, not two */
P .video-section { padding-top: clamp(24px, 4vh, 48px); }
P .hero-video-card { border-radius: 2px; }
P .hero-card-social-text { color: rgba(255,255,255,0.7); }
html[data-theme="light"] P .hero-video-card { box-shadow: 0 24px 64px rgba(15,26,42,0.18); }
@media (max-width: 768px) { P .video-section { padding-top: 24px; } }
'''
css = (HEAD + HERO).replace('P ', P + ' ').replace('NOISE', NOISE).replace('PAGELIST', ', '.join(PAGES))
css += "\n/* ═══ The use-case route's rules for the shared sections (card grid, how-it-works, FAQ, footer CTA, scaffolding, over-hero nav), re-scoped ═══ */\n"
css += '\n'.join(picked) + '\n' + '\n'.join(keyframes) + '\n'
# last: its seam trim has to follow the re-scoped `.section` unit it overrides (equal weight, source order decides)
css += VIDEO.replace('P ', P + ' ')
(repo / 'src/styles/builder-light-kit.css').write_text(css)
print(f'wrote builder-light-kit.css: {len(css)} bytes, {len(picked)} route blocks re-scoped, {len(keyframes)} keyframes')
